QuanLyKhachSan/Areas/Admin/Controllers/ReportDetailController.cs
using QuanLyKhachSan.Areas.Admin.Models.AjaxModel;
using QuanLyKhachSan.Areas.Admin.ViewModel;
using QuanLyKhachSan.Entity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyKhachSan.Areas.Admin.Controllers
{
    public class ReportDetailController : BaseController
    {
        DataEntities db = new DataEntities();
        [Authorize]
        public ActionResult Index()
        {
            ReportDetail report = new ReportDetail();
            report.Parameter = new Parameter();
            report.Parameter.ToDate = DateTime.Now.ToString("dd/MM/yyyy");
            report.Parameter.FromDate = DateTime.Now.Date.AddMonths(-1).ToString("dd/MM/yyyy");
            return View(report);
        }
        [Authorize]
        public ActionResult ViewReport(Parameter parameter)
        {
            ReportDetail report = new ReportDetail();
            report.Parameter = parameter;
            DateTime fromD,toD;
            if (!DateTime.TryParseExact(parameter.FromDate, "d/M/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out fromD))
                fromD = DateTime.MinValue;
            if (!DateTime.TryParseExact(parameter.ToDate, "d/M/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out toD))
                toD = DateTime.MaxValue;
            else
                toD = toD.AddDays(1);
            var ios = from io in db.InOuts
                      where io.Status == 1 && fromD <= io.PayDate && io.PayDate < toD
                      group io by new {io.PayDate,io.Room.RoomName,io.RoomId} into g
                      orderby g.Key ascending
                      select new {
                          Day = g.Key.PayDate,
                          RoomId = g.Key.RoomId,
                          RoomName = g.Key.RoomName,
                          Count = g.Count(),
                          RoomServiceAmount = g.Sum(o => o.RoomServiceAmount),
                          TotalAmount = g.Sum(o => o.TotalAmount)
                      };
            List<Detail2> details = new List<Detail2>();
            foreach (var inout in ios)
            {
                Detail2 d = new Detail2();
                d.Day = inout.Day.ToString("dd/MM/yyyy");
                d.RoomName = inout.RoomName;
                d.Count = inout.Count;
                d.RoomServiceAmount = inout.RoomServiceAmount;
                d.TotalAmount = inout.TotalAmount;
                d.OtherServiceDetails = new List<OtherServiceDetail>();
                var otherServices = from ioo in db.InOut_OtherServices
                                    where ioo.InOut.Status == 1 && ioo.InOut.PayDate == inout.Day && ioo.InOut.RoomId == inout.RoomId
                                    group ioo by new { ioo.OtherService.ServiceName } into g
                                    orderby g.Key ascending
                                    select new
                                    {
                                        OtherServiceName = g.Key.ServiceName,
                                        Quantity = g.Sum(o=>o.Quantity),
                                        OtherServiceAmount = g.Sum(o=>o.Quantity*o.OtherService.Price),
                                    };
                foreach (var os in otherServices)
                {
                    d.OtherServiceDetails.Add(new OtherServiceDetail() 
                                                { 
                                                    OtherServiceName = os.OtherServiceName,
                                                    Quantity = os.Quantity,
                                                    OtherServiceAmount = os.OtherServiceAmount
                                                });
                }
                details.Add(d);
            }
            report.Details = details.ToArray();
            return View("Index",report);
        }
    }
}

QuanLyKhachSan/Areas/Admin/Views/ReportDetail/Detail2Partial.cshtml
@model IEnumerable<QuanLyKhachSan.Areas.Admin.ViewModel.Detail2>

@{
    decimal totalAmount = 0;
    string format = "#,#0.#;-#,#0.#";
    if (Model != null && Model.Count()>0)
    {
        <div class="container">
          <div class="row">
            <div class="col-xs-3 text-center"><strong>Ngày</strong></div>
            <div class="col-xs-2 text-center"><strong>Phòng</strong></div>
            <div class="col-xs-3 text-center"><strong>Dịch vụ</strong></div>
              <div class="col-xs-2 text-center"><strong>Số lượng</strong></div>
            <div class="col-xs-2 text-center"><strong>Số tiền</strong></div>
          </div>
        @foreach (var item in Model)
        {
            totalAmount += item.TotalAmount;
          <div class="row">
            <div class="col-xs-3 text-center">@item.Day</div>
            <div class="col-xs-2 text-center">@item.RoomName</div>
            <div class="col-xs-3 text-right">Dịch vụ phòng</div>
            <div class="col-xs-2 text-right">@item.Count</div>
            <div class="col-xs-2 text-right">@item.RoomServiceAmount.ToString(format)</div>
          </div>   
          foreach (var otherService in item.OtherServiceDetails)
          {
              <div class="row">
                <div class="col-xs-3 text-center">&#008;</div>
                <div class="col-xs-2 text-center">&#008;</div>
                <div class="col-xs-3 text-right">@otherService.OtherServiceName</div>
                <div class="col-xs-2 text-right">@otherService.Quantity</div>
                <div class="col-xs-2 text-right">@otherService.OtherServiceAmount.ToString(format)</div>
              </div> 
          }
          <div class="row">
            <div class="col-xs-8 text-right"><b>Tổng cộng trong ngày</b></div>
            <div class="col-xs-4 text-right"><b>@item.TotalAmount.ToString(format) </b></div>
          </div>          
        }
        </div>
        <br />
        <div class="container">
            <div class="row">
                <div class="col-xs-8 text-right"><b>Tổng doanh thu</b></div>
                <div class="col-xs-4 text-right"><b>@totalAmount.ToString(format) </b></div>
              </div> 
        </div>  
        <br/><br/><br/><br/>
    }
}
         
<br/><br/><br/><br/><br/>
<style media="all">

    .row .row {
      margin-top: 10px;
      margin-bottom: 0;
    }
    [class*="col-"] {
      padding-top: 15px;
      padding-bottom: 15px;
      background-color: #eee;
      background-color: rgba(86,61,124,.15);
      border: 1px solid #ddd;
      border: 1px solid rgba(86,61,124,.2);
    }

</style>

QuanLyKhachSan/Areas/Admin/Views/ReportDetail/Index.cshtml
@model QuanLyKhachSan.Areas.Admin.ViewModel.ReportDetail
@{
    ViewBag.Title = "Báo cáo chi tiết";
    Layout = "~/Areas/Admin/Views/Shared/_layout.cshtml";
}
<div class="page-header">
    <h1>Báo cáo chi tiết</h1>
</div>
<div class="container" style="width:60%">
    <div class="jumbotron">
        <div class="row">
            @using (Html.BeginForm("ViewReport", "ReportDetail", FormMethod.Post))
            {
                @Html.ValidationSummary(true)
                <fieldset>
                    <legend>Tham số</legend>
                    <div class="input-group">
                        <span class="input-group-addon">@Html.LabelFor(model => model.Parameter.FromDate)</span>
                        <input id="fromDate" name="FromDate" class="form-control" type="text" value="@Model.Parameter.FromDate">
                        <span class="input-group-addon">@Html.LabelFor(model => model.Parameter.ToDate)</span>
                        <input id="toDate" name="ToDate" class="form-control" type="text" value="@Model.Parameter.ToDate">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit">Xem</button>
                        </div>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</div>
<style>
    div.datepicker.dropdown-menu {
        top: 320px;
    }
</style>
@section scripts
{
    <script>
        $(function () {
            window.prettyPrint && prettyPrint();
            var fromdate = $('#fromDate').datepicker({ format: 'dd/mm/yyyy' }).on('changeDate', function (ev) {
                fromdate.hide();
            }).data('datepicker');
            var todate = $('#toDate').datepicker({ format: 'dd/mm/yyyy' }).on('changeDate', function (ev) {
                todate.hide();
            }).data('datepicker');
        });
    </script>
}
@if (Model.Details != null)
{
    @Html.Partial("Detail2Partial", Model.Details)
}